# 복습하기

## Computer vision의 사용 예

<img src="https://github.com/user-attachments/assets/6e1be390-77fe-4b6e-b7aa-d1f4ef43f0d2" width="1000">

출처: https://cs231n.stanford.edu/slides/2017/cs231n_2017_lecture11.pdf

## Neural Network

![image](https://github.com/user-attachments/assets/205506a5-45fe-4f5a-b3a3-340a4a81eb69)

출처:https://towardsdatascience.com/the-concept-of-artificial-neurons-perceptrons-in-neural-networks-fab22249cbfc


| 특성          | 생물학적 뉴런                          | 인공 신경망                           |
|---------------|---------------------------------------|---------------------------------------|
| **구조**  | 수상돌기, 세포핵, 축삭          | 입력 노드, 은닉층, 출력 노드          |
| **신호 전달** | 전기적 신호와 화학적 신호 전달          | 수학적 함수와 가중치를 통한 정보 전달 |
| **학습 방식** | 시냅스 가소성을 통한 학습              | 손실 함수 최소화를 통한 학습(역전파) |
| **정보 저장** | 시냅스 강도 변화                       | 가중치 및 편향                       |

![image](https://user-images.githubusercontent.com/12128784/140010649-40dce697-5e93-4b64-ab3a-3c547c932ad1.png)



![image](https://user-images.githubusercontent.com/12128784/111853348-004e6180-895e-11eb-9fd9-8ebfca052b0a.png)




![image](https://github.com/user-attachments/assets/f0ce59f2-a7ae-4043-b834-28d0586872b0)


![image](https://github.com/user-attachments/assets/73a3d9f8-2665-4d46-8071-5aba935849e8)

출처: https://medium.com/@Suraj_Yadav/in-depth-knowledge-of-convolutional-neural-networks-b4bfff8145ab

## FC-layer sample

![image](https://user-images.githubusercontent.com/12128784/140010649-40dce697-5e93-4b64-ab3a-3c547c932ad1.png)


In [ ]:
# Make Tensor 10,10. dtype=int
import torch

fc1 = torch.nn.Linear(4, 3)

fc1.weight.data = torch.tensor([[0.1, 0.3, 0.1, 0.1],
                                [0.1, 0.3, 0.4, 0.1],
                                [0.3, 0.3, 0.1, 0.2]], dtype=torch.float)
fc1.bias.data = torch.tensor([3, 6, 9], dtype=torch.float)


input = torch.tensor([1, 2, 3, 4], dtype=torch.int).float()
print(input)
print("=" * 100)
print(fc1.weight.data)
print(fc1.bias.data)
print("=" * 100)
output = fc1(input)
print(output) 

# CNN(Convolution Neural Network)

![ezgif com-animated-gif-maker](https://github.com/user-attachments/assets/f726212f-95f6-4408-9cc4-62da36c38086)

출처: https://www.youtube.com/watch?v=pj9-rr1wDhM&t=336s



![image](https://github.com/user-attachments/assets/1203400f-92ee-4561-995b-a48c42007178)

출처: https://medium.com/@Suraj_Yadav/in-depth-knowledge-of-convolutional-neural-networks-b4bfff8145ab

0 * 0 + -1 * 0 + 0 * 0 +

0 * -1 + 60 * 5 + 113 * -1

0 * 0 + 73 * -1 + 121 * 0 = 114

![1_O06nY1U7zoP4vE5AZEnxKA](https://github.com/user-attachments/assets/7238bdaa-65ad-458a-84a7-b16ab8a4362e)

출처: https://medium.com/@Suraj_Yadav/in-depth-knowledge-of-convolutional-neural-networks-b4bfff8145ab

## Stride

![1_Bmx3AHBhx0D5OmBSxtY6gw](https://github.com/user-attachments/assets/868b19c8-62c3-4b2b-94c2-4b472445924f)

![1_X22-wmPcir4y5VoeqDyvWg](https://github.com/user-attachments/assets/a1df99ea-096f-438b-b997-caa935f72010)

출처: https://medium.com/@Suraj_Yadav/in-depth-knowledge-of-convolutional-neural-networks-b4bfff8145ab

## Convolution Filter


![image](https://github.com/user-attachments/assets/c1548757-cf97-4d55-ae81-e18b937a344a)

![image](https://github.com/user-attachments/assets/081a29da-9095-4438-a58f-66607485631b)

![image](https://github.com/user-attachments/assets/d7b4f327-d128-4da9-ac59-fe5f131acd5a)

![image](https://github.com/user-attachments/assets/52666246-3017-4a8d-9b3d-6ea72099f2ae)

![image](https://github.com/user-attachments/assets/34e38a4e-25d8-4ca0-acf7-aeb8b9d3ab47)

![image](https://github.com/user-attachments/assets/8cd429d8-a56f-4aeb-be34-6a463731a77a)


![image](https://github.com/user-attachments/assets/8706cd10-4600-42d7-9445-5740a2ecd93d)


![image](https://github.com/user-attachments/assets/971729ad-002e-4864-bd61-c3ac59c70ec9)

![image](https://github.com/user-attachments/assets/f96372d8-a96d-45c4-bb34-d4aaf74314c3)


출처: https://dev.to/sandeepbalachandran/machine-learning-convolution-with-color-images-2p41

## CNN 예제

In [ ]:
import torch

cnn1 = torch.nn.Conv2d(2, 3, kernel_size=2, stride=1, padding=1) 

cnn1.weight.data = torch.randint(low=1, high=5, size=(3, 2, 2, 2), dtype=torch.int).float()
cnn1.bias.data = torch.tensor([1,2,3]).float()



input = torch.randint(low=0, high=3, size=(2, 5, 5), dtype=torch.int).float()
print(input)
print("=" * 100)
print(cnn1.weight.data)
print(cnn1.bias.data)
print("=" * 100)
output = cnn1(input)
print(output)


tensor([[[2., 2., 1., 0., 2.],
         [0., 2., 0., 2., 2.],
         [2., 1., 0., 0., 2.],
         [2., 0., 1., 1., 0.],
         [0., 2., 0., 2., 0.]],

        [[1., 2., 2., 0., 2.],
         [2., 1., 0., 2., 2.],
         [1., 2., 1., 2., 1.],
         [1., 2., 0., 0., 2.],
         [0., 2., 0., 2., 1.]]])
tensor([[[[2., 1.],
          [2., 4.]],

         [[3., 1.],
          [1., 4.]]],


        [[[2., 3.],
          [3., 1.]],

         [[1., 1.],
          [4., 3.]]],


        [[[3., 4.],
          [1., 4.]],

         [[3., 3.],
          [1., 1.]]]])
tensor([1., 2., 3.])
tensor([[[13., 22., 19.,  5., 17.,  7.],
         [12., 26., 19., 25., 27., 17.],
         [15., 27., 16., 14., 29., 16.],
         [16., 24., 16., 12., 20., 10.],
         [ 4., 26., 14., 20., 15.,  8.],
         [ 1.,  5., 11.,  5., 12.,  4.]],

        [[ 7., 20., 23., 13., 10., 16.],
         [15., 28., 23., 14., 32., 22.],
         [ 9., 28., 21., 20., 29., 18.],
         [14., 28., 16.,  9., 20., 15

In [ ]:

cnn1 = torch.nn.Conv2d(3, 5, kernel_size=3, stride=2, padding=1)
input = torch.randint(low=0, high=3, size=(3, 32, 32), dtype=torch.int).float()

print("Input shape : ", input.shape)
output = cnn1(input)
print("Output shape: ", output.shape)


Input shape :  torch.Size([3, 32, 32])
Output shape:  torch.Size([5, 16, 16])


## CNN의 장점

Convolutional Layer(CNN 레이어)는 Fully Connected(FC) Layer에 비해 몇 가지 중요한 장점이 있습니다. 이러한 장점은 CNN이 특히 이미지 데이터에서 뛰어난 성능을 발휘하게 하는 요인입니다.

### 1. 공간적 관계 유지
> **FC Layer**: 모든 입력 뉴런이 모든 출력 뉴런에 연결되므로 입력의 공간적 구조가 무시됩니다. 따라서 FC Layer는 입력 데이터의 공간적 관계를 인식할 수 없습니다.

> **Convolution Layer**: 입력 이미지의 작은 영역(리셉티브 필드)에 대해서만 필터를 적용합니다. 이로 인해 CNN은 인접 픽셀 간의 관계를 유지하고 학습할 수 있으며, 이미지의 공간적 패턴을 인식하는 데 유리합니다.

### 2. 파라미터 수 감소
> **FC Layer**: 입력과 출력의 모든 뉴런이 연결되므로, 입력 크기와 출력 크기에 따라 파라미터 수가 급격히 증가합니다.

> **Convolution Layer**: 동일한 필터를 이미지 전체에 걸쳐 적용하므로, 파라미터 수가 크게 줄어듭니다. 이는 파라미터 공유(parameter sharing)로 인해 가능하며, 모델이 더 효율적이고 메모리 절약적입니다.

### 3. 변환 불변성(Translation Invariance)
> **FC Layer**: 입력 데이터의 위치 변화에 민감하여, 데이터의 이동이나 왜곡에 취약합니다.

> **Convolution Layer**: 필터가 이미지의 모든 위치에 동일하게 적용되기 때문에, 객체의 위치 변화에 대해 비교적 강인합니다. 이는 이미지 내 객체의 위치가 약간 변해도 그 특징을 잘 인식할 수 있게 합니다.

# Pooling

![_2024_08_06_14_10_21_153-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/a25f6253-c4d9-44e7-af42-9e7edc1c3c3f)

출처: https://www.youtube.com/watch?v=pj9-rr1wDhM&t=336s

![image](https://github.com/user-attachments/assets/4c516742-0a3b-4dbf-80bc-4feadd1534cf)

In [ ]:
input = torch.tensor([[[12 , 20 , 30, 0 ],
                       [8  , 12 , 2 , 0 ],
                       [34 , 70 , 37, 4 ],
                       [112, 100, 25, 12]]])

MaxPool = torch.nn.MaxPool2d(kernel_size=2, stride=1, padding=1)
Output = MaxPool(input)
print(Output)

tensor([[[ 12,  20,  30,  30,   0],
         [ 12,  20,  30,  30,   0],
         [ 34,  70,  70,  37,   4],
         [112, 112, 100,  37,  12],
         [112, 112, 100,  25,  12]]])
