# 텐서(Tensor)



텐서(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조입니다.

PyTorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)합니다.

텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 NumPy의 ndarray와 유사합니다.

텐서는 또한 뒤에서 살펴볼 자동 미분(automatic differentiation)에 최적화되어 있습니다.

ndarray에 익숙하다면 Tensor API를 바로 사용할 수 있을 것입니다. 아니라면, 아래 내용을 함께 보시죠!

<img src = 'https://media.vlpt.us/images/mingki/post/e0cdf6b1-cfd0-4a64-82d1-0c489237f1c2/array_shape.png' width="500">

출처: https://github.com/elegant-scipy/elegant-scipy/blob/master/figures/NumPy_ndarrays_v2.png

In [ ]:
import torch
import numpy as np

### 텐서(tensor) 초기화

이번 섹션에서는 다양한 방법을 이용하여 tensor를 초기화해보겠습니다.



#### List 배열로부터 생성하기

텐서는 List로 생성할 수 있습니다. (그 반대도 가능합니다)



In [ ]:
data = [[1, 2],[3, 4]]  # input: 2x2 중첩리스트
x_data = torch.tensor(data)
print(x_data) # shape(2,2) tensor 출력
print(x_data.tolist()) # tensor에서 list로 다시 전환


# torch.tensor()는 데이터를 복사하여 텐서를 만듭니다(원본 리스트와 메모리 공유 X) 반면, torch.as_tensor()는 가능하면 원본 데이터를 공유하려고 시도합니다(메모리 효율적)
# 따라서, 원본 데이터를 변경하면 torch.as_tensor()로 생성된 텐서도 영향을 받을 수 있습니다.

tensor([[1, 2],
        [3, 4]])
[[1, 2], [3, 4]]


#### NumPy 배열로부터 생성하기

텐서는 NumPy 배열로 생성할 수 있습니다. (그 반대도 가능합니다)



In [ ]:
data = [[1, 2],[3, 4]]
np_array = np.array(data) # input: 2x2 numpy array
x_np = torch.from_numpy(np_array)
print(x_np) # 넘파이와 메모리 공유 → 한쪽을 수정하면 다른 쪽도 변함
print(x_np.numpy()) # 다시 넘파이 배열 반환(여기도 공유됨)


# 정리: torch.tensor(np_array)는 복사이고, torch.from_numpy(np_array)는 공유입니다.

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
[[1 2]
 [3 4]]


#### 무작위(random) 또는 상수(constant) 값을 사용하기:

`shape` 은 텐서의 차원(dimension)을 나타내는 튜플(tuple)로, 아래 함수들에서는 출력 텐서의 차원을 결정합니다.



In [ ]:
# 모델의 가중치 조기화, 테스트용 입력 등에서 랜덤/상수 텐서가 자주 사용됩니다

shape = (2,3) # tuple 형태의 텐서 크기 지정
rand_tensor = torch.rand(shape) # 균등분포에서 무작위 값으로 채워진 텐서 생성
ones_tensor = torch.ones(shape) # 모든 원소가 1인 텐서 생성
zeros_tensor = torch.zeros(shape) # 모든 원소가 0인 텐서 생성

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4758, 0.3400, 0.1232],
        [0.2574, 0.5191, 0.0304]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# 기존 텐서와 동일한 shape/dtype/device를 가지는 새 텐서를 쉽게 만듭니다 -> 파이프라인에서 편리하게 사용 가능
a = torch.ones_like(rand_tensor)
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


#### 텐서의 속성(Attribute)

텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치(device)에 저장되는지를 나타냅니다.



In [ ]:
tensor = torch.rand(3,4)

print(f"Tensor: \n{tensor}\n")
print(f"Shape of tensor: {tensor.shape}") # 텐서가 어떻게 생겼는지 형태 확인
print(f"Datatype of tensor: {tensor.dtype}") # 텐서의 데이터 타입 확인
print(f"Device tensor is stored on: {tensor.device}") # 텐서가 저장된 디바이스 확인 -> cpu or gpu

Tensor: 
tensor([[0.6126, 0.1280, 0.0708, 0.4639],
        [0.3376, 0.5723, 0.5151, 0.1004],
        [0.2964, 0.0375, 0.5704, 0.9532]])

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### 텐서 연산


#### NumPy식의 표준 인덱싱과 슬라이싱:



In [29]:
# 파이토치는 넘파이와 거의 동일한 인덱싱 규칙을 사용 -> 행/열 접근, 슬라이스, 부분 대입 등
tensor = torch.ones(4, 4)

print(tensor)
print('First row: ',tensor[0]) # 0번째 행 (shape=(4,))
print('Last row: ', tensor[-1]) # 마지막 행 (shape=(4,))
print('First column: ', tensor[:, 0]) # 모든 행의 0번째 열 (shape=(4,))
print('Last column:', tensor[:, -1]) # 모든 행의 마지막 열 (shape=(4,))

tensor[:,1] = 0 # 두 번째 열을 0으로 바꾼 후의 텐서
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row:  tensor([1., 1., 1., 1.])
Last row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### 텐서 합치기

`torch.cat` 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있습니다.



In [ ]:
# 배치/특성 차원 등에서 여러 텐서를 축 기준으로 연결

# dim=1 기준으로 4x4 텐서 3개를 연결하여 4x12 텐서 생성
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
# 연결하려는 축 외의 나머지 차원 크기가 동일해야 합니다.

# dim=0 기준으로 4x4 텐서 3개를 연결하여 12x4 텐서 생성
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### 산술 연산(Arithmetic operations)

In [ ]:
# 기본적으로 element-wise 연산(같은 위치의 원소들끼리 연산)이 수행

a = torch.tensor([1,2,3])
b = torch.tensor([3,4,5])

# 두 텐서간의 합
print("a + b : ", a+b)

# 두 텐서간의 차
print("a - b : ", a-b)


a + b :  tensor([4, 6, 8])
a - b :  tensor([-2, -2, -2])


In [33]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
# 행렬 곱의 출력 shape: (m×k) @ (k×n) → (m×n)

data = torch.tensor([[1,2],[3,4]]) # 입력값 2x2 텐서

print("data : ", data)
print("data.T : ", data.T) # 전치행렬, 1D 텐서는 .T가 변화 없음

y1 = data @ data.T
y2 = data.matmul(data.T)
y3 = torch.matmul(data, data.T)

# y1, y2, y3 모두 같은 결과(2×2 행렬 곱 결과)
print(y1)
print(y2)
print(y3)

# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = data * data              # * / .mul() / torch.mul() → 원소별 곱
z2 = data.mul(data)           # @ / .matmul() / torch.matmul() → 행렬 곱
z3 = torch.mul(data, data)

print(z1)
print(z2)
print(z3)


data :  tensor([[1, 2],
        [3, 4]])
data.T :  tensor([[1, 3],
        [2, 4]])
tensor([[ 5, 11],
        [11, 25]])
tensor([[ 5, 11],
        [11, 25]])
tensor([[ 5, 11],
        [11, 25]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])


#### 비선형 연산


딥러닝에서 활성화 함수(ReLU, Softmax, Sigmoid)는 신경망이 “비선형성(Non-linearity)”을 학습할 수 있게 만드는 핵심 요소입니다.

만약 활성화 함수가 없다면 신경망은 단순한 선형 모델이 되어버립니다.

In [ ]:
# 입력: 파이썬 list -> 1차원 텐서, torch.FloatTensor, shape=(6,)
input = torch.tensor([-2, -1, 0, 1, 2, 3]).float()
# .float()로 자료형을 float32로 변환
# 왜 why? -> 신경망 활성화 함수는 실수값을 입력으로 받기 때문 즉, 대부분의 활성화 함수는 실수(float) 연산을 하기 때문에 float로 만들 필요가 있음
# 정수 텐서는 활성화 함수 적용 시 자동 캐스팅 또는 오류 가능

#ReLU
ReLU = torch.nn.ReLU()
print("ReLU : ", ReLU(input)) # ReLU(input)을 통해 ReLU 활성화 함수 적용


#softmax
m = torch.nn.Softmax(dim=0) # Softmax 모듈 생성 (dim=0 → 벡터 전체에 대해 softmax 계산)
input = torch.tensor([-2, -1, 1, 2, 3]).float()
print("softamx : " , m(input))

#sigmoid
print("sigmoid : " , torch.sigmoid(input))


ReLU :  tensor([0., 0., 0., 1., 2., 3.])
softamx :  tensor([0.0044, 0.0120, 0.0886, 0.2407, 0.6543])
sigmoid :  tensor([0.1192, 0.2689, 0.7311, 0.8808, 0.9526])


# ReLU란? 
ReLU(x) = max(0, x)
- ReLU(Rectified Linear Unit)는 신경망에서 널리 사용되는 활성화 함수 중 하나
- ReLU 함수는 입력값이 0보다 크면 그대로 출력하고, 0 이하이면 0을 출력하는 간단한 비선형 함수
- 의도: 음수 제거 → 양수만 통과 → 비선형성 부여, 기울기 소실 문제(Vanishing Gradient)를 줄여 딥러닝에서 가장 널리 사용


# Softmax란? 
다중 클래스 분류 문제에서 출력층에서 주로 사용되는 활성화 함수
- Softmax 함수는 입력 벡터의 각 원소를 지수 함수로 변환한 후, 이들의 합으로 나누어 각 원소가 0과 1 사이의 값이 되도록 만듦
- 이렇게 변환된 값들은 전체 합이 1이 되기 때문에 확률 분포로 해석할 수 있음
- 다중 클래스 분류(Classification)에서 마지막 출력층에 보통 사용

#### 단일-요소(single-element) 텐서

텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우,
``item()`` 을 사용하여 Python 숫자 값으로 변환할 수 있습니다:



In [34]:
data

tensor([[1, 2],
        [3, 4]])

In [ ]:
agg = data.sum() # 텐서 전체 원소를 모두 더함, 스칼라 텐서 반환(0차원)
print(agg, type(agg))
agg_item = agg.item() # 0차원 텐서를 숫자(int 또는 float)로 변환
print(agg_item, type(agg_item)) # 텐서 값을 Python 변수(예: 숫자형)로 변환할 때 필요 -> 로그 출력, 손실 값 저장, 리스트에 기록할 때 자주 사용

tensor(10) <class 'torch.Tensor'>
10 <class 'int'>


### 역전파(Backpropagation)

tensor를 사용하면 이전에 배웠던 역전파를 굉장히 간단하게 사용할 수 있습니다.

<img src="https://user-images.githubusercontent.com/12128784/163274773-24e4385f-ed5c-498b-a1f6-55525c63e48a.png" width="1000">

<img src="https://user-images.githubusercontent.com/12128784/129708066-2659df51-5be5-4a8f-98a5-8877a30b1f23.png" width="1000">

출처: http://cs231n.stanford.edu/slides/2021/lecture_4.pdf

In [ ]:
a = torch.tensor([1.0,2.0,3.0], requires_grad=True)
b = torch.tensor([2.0,3.0,4.0], requires_grad=True)
c = torch.tensor([4.0,5.0,6.0], requires_grad=True)
d = torch.tensor([7.0,8.0,9.0], requires_grad=True)
print(a.grad)

# 아직 backward를 호출하지 않았기 때문에 a.grad는 None

None


In [35]:
a = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
b = torch.tensor([2.0, 3.0, 4.0], requires_grad=True)

print("초기 a.grad:", a.grad)  # None

y = a * b
z = y.sum()

print("z:", z)

z.backward()  # 미분 수행

print("a.grad:", a.grad)  # tensor([2., 3., 4.])
print("b.grad:", b.grad)  # tensor([1., 2., 3.])

초기 a.grad: None
z: tensor(20., grad_fn=<SumBackward0>)
a.grad: tensor([2., 3., 4.])
b.grad: tensor([1., 2., 3.])


#### 덧셈에 대한 Auto Grad

In [ ]:
y = a+b 
print("y : ", y.data)
print("y_grad_fn : ", y.grad_fn) # .grad_fn “이 텐서가 어떤 연산에 의해 만들어졌는지” 나타내는 자동미분 함수


# PyTorch에서 requires_grad=True 텐서끼리 연산을 하면 자동으로 계산 그래프(Computation Graph)가 만들어짐
# 즉, y = a + b → AddBackward0 라는 grad_fn 생성, 이 정보 덕분에 backward() 호출 시 + 연산의 미분(∂y/∂a = 1, ∂y/∂b = 1)를 알고 있음
# 출력: y 텐서 + y.grad_fn = AddBackward0

y :  tensor([3., 5., 7.])
y_grad_fn :  <AddBackward0 object at 0x000001BE9A8DBA90>


#### 뺄셈에 대한 Auto Grad

In [ ]:
y = y-c   # 기존 y 에서 c 를 뺌 → y = (a+b)-c
print("y : ", y.data)
print("y_grad_fn : ", y.grad_fn)

# 뺄셈도 미분 규칙이 단순하기 때문에 자동으로 그래프가 확장됨, ∂y/∂c = -1
# 즉, autograd는 계속해서 새로운 연산을 그래프에 연결하며 추적

y :  tensor([-1.,  0.,  1.])
y_grad_fn :  <SubBackward0 object at 0x000001BE8038A500>


#### 곱셈에 대한 Auto Grad

In [ ]:
y = y*d # 곱셈이 추가됨 → y = (a + b - c) * d
print("y : ", y.data)
print("y_grad_fn : ", y.grad_fn)

y :  tensor([-7.,  0.,  9.])
y_grad_fn :  <MulBackward0 object at 0x000001BE80389450>


#### RELU 연산에 대한 Auto Grad

In [ ]:
y = ReLU(y)
print("y : ", y.data)
print("y_grad_fn : ", y.grad_fn)

# y 값이 음수면 0으로 만들고 양수면 그대로(pass), 즉, ReLU의 미분 규칙에 따라 ∂y/∂input = 0 (input ≤ 0), 1 (input > 0)
# 따라서, ReLU 연산도 자동으로 그래프에 추가되어 추적

y :  tensor([0., 0., 9.])
y_grad_fn :  <ReluBackward0 object at 0x000001BE9731A9E0>


#### Summation에 대한 Auto Grad

In [ ]:
y = torch.sum(y) # 텐서의 모든 원소를 하나의 값(스칼라)으로 -> backward()를 호출하려면 출력이 반드시 스칼라여야 한다./ backward() 호출 시 모든 위치에 1이 전달됨
print("y : ", y.data)
print("y_grad_fn : ", y.grad_fn)

y :  tensor(9.)
y_grad_fn :  <SumBackward0 object at 0x000001BE9731A9E0>


#### Gradient 자동 계산

Gradient를 자동 계산하기 위해서는 `requires_grad`가 필요합니다. 해당 작업을 해주지 않을 경우 오류가 발생합니다.

In [21]:
a = torch.tensor([1.0,2.0,3.0], requires_grad=True)
b = torch.tensor([1.0,2.5,4.0], requires_grad=True)
y = a*b
z = y.sum()
z.backward()
print(a.grad)
print(b.grad)

tensor([1.0000, 2.5000, 4.0000])
tensor([1., 2., 3.])


그러나 단순히 `backward()` 함수를 호출하는 것만으로는 텐서 값이 자동으로 업데이트되지 않습니다. 

`backward()`는 기울기를 계산하는 역할을 하지만, 실제 파라미터의 값을 변경하려면 추가적인 과정이 필요합니다.

파라미터의 값을 자동으로 업데이트하려면 `torch.nn.Parameter`를 사용하여 텐서를 학습 가능한 파라미터로 설정해야 하며, 그 후에 옵티마이저(optimizer)를 사용하여 역전파(back-propagation) 과정을 통해 값을 조정할 수 있습니다. 

이를 통해 기울기가 계산되고, 그 기울기를 바탕으로 파라미터의 값이 갱신됩니다.

optimizer는 손실 함수(loss function)를 최소화하는 방향으로 파라미터를 업데이트하여, 결과적으로 모델이 global minima(전역 최소점)에 도달할 수 있도록 돕는 역할을 합니다. 

여러 가지 최적화 알고리즘이 있으며, 가장 대표적인 것으로는 SGD, Adam 등이 있습니다. 이러한 옵티마이저는 파라미터 업데이트 규칙을 정의하며, 학습 과정을 통해 모델 성능을 점진적으로 향상시킵니다.

In [ ]:
import torch.optim as optim

device = "cuda" if torch.cuda.is_available() else "cpu"

print(d)
print("=" * 100)

# Parameter 등록
a = torch.nn.Parameter(a)
b = torch.nn.Parameter(b)
c = torch.nn.Parameter(c)
d = torch.nn.Parameter(d)

optimizer = optim.SGD([a,b,c,d], lr = 3.0)

gt = torch.tensor([10.0,30.0,50.0])

y = a+b
y = y-c
y = y*d
y = torch.sigmoid(y)
loss = torch.sum(y-gt)


print("loss: ", loss)

loss.backward() # loss를 기준으로 backward() 수행, 각각의 gradient 출력
print("a.grad: ", a.grad)
print("b.grad: ", b.grad)
print("c.grad: ", c.grad)
print("d.grad: ", d.grad)

optimizer.step() # 계산된 gradient를 기반으로 파라미터(Weights)를 실제로 업데이트(update step) 수행
print(d) # 업데이트 이후 d 값 출력

tensor([7., 8., 9.], requires_grad=True)
loss:  tensor(-88.9821, grad_fn=<SumBackward0>)
a.grad:  tensor([5.8207e-06, 1.4130e-01, 1.1103e-03])
b.grad:  tensor([5.8207e-06, 1.4130e-01, 1.1103e-03])
c.grad:  tensor([-5.8207e-06, -1.4130e-01, -1.1103e-03])
d.grad:  tensor([-1.6631e-06, -8.8314e-03,  1.2337e-04])
Parameter containing:
tensor([7.0000, 8.0265, 8.9996], requires_grad=True)
